# Generated by Django 4.2.27 on 2026-01-03 16:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, help_text='e.g. Lead Lecturer, Lab Assistant', max_length=100, null=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('course_module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_assignments', to='Admin.coursemodule')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('course_module', 'staff')},
            },
        ),
    ]
