# Generated by Django 4.2.27 on 2026-01-17 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_coursestaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='availability',
            field=models.BooleanField(default=True),
        ),
    ]
