# Generated by Django 4.2.27 on 2026-01-21 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_timetableslot'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab',
            name='lab_code',
            field=models.CharField(default='NEW', max_length=20),
        ),
    ]
