# Generated by Django 4.2.27 on 2026-01-21 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_lab_lab_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableslot',
            name='note',
            field=models.CharField(blank=True, help_text='Extra info or activity name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='slot_date',
            field=models.DateField(help_text='The specific calendar date for this session'),
        ),
        migrations.AlterField(
            model_name='timetableslot',
            name='time_range',
            field=models.CharField(help_text='e.g., 08:00 - 09:00', max_length=50),
        ),
    ]
