# Generated by Django 4.2.27 on 2026-01-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_alter_timetableslot_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursestaff',
            name='role',
            field=models.CharField(blank=True, choices=[('Lecturer', 'Lecturer'), ('Demonstrator', 'Demonstrator')], help_text='e.g. Lecturer, Demonstrator', max_length=100, null=True),
        ),
    ]
