# Generated by Django 4.2.27 on 2026-01-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_alter_coursestaff_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='degree',
            name='semester',
            field=models.CharField(choices=[('1', 'Semester 1'), ('2', 'Semester 2')], max_length=1),
        ),
    ]
