# Generated by Django 6.0.1 on 2026-01-27 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authenticate', '0002_usertable_reset_token_usertable_reset_token_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertable',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='usertable',
            name='reset_otp_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
